import React, { useState, useEffect } from 'react';
import './AdminDashboard.css';

function AdminDashboard() {
  const [students, setStudents] = useState([]);
  const [guardians, setGuardians] = useState([]);
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    setLoading(true);
    setError('');
    try {
      const [studentsResult, guardiansResult, logsResult] = await Promise.all([
        window.electron.getStudents(),
        window.electron.getGuardians(),
        window.electron.getVerificationLogs(),
      ]);

      if (studentsResult.success) {
        setStudents(studentsResult.data || []);
      } else {
        setError(studentsResult.error || 'Failed to load students');
      }

      if (guardiansResult.success) {
        setGuardians(guardiansResult.data || []);
      } else {
        setError(guardiansResult.error || 'Failed to load guardians');
      }

      if (logsResult.success) {
        setLogs(logsResult.data || []);
      }
    } catch (err) {
      setError('Error loading data: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handlePrintReport = () => {
    const reportData = {
      students,
      guardians,
      generatedAt: new Date().toLocaleString(),
    };

    const content = `
      <html>
        <head>
          <title>Guardian Verification System - Report</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { color: #667eea; }
            table { border-collapse: collapse; width: 100%; margin: 20px 0; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
            th { background: #667eea; color: white; }
            .section { page-break-after: always; margin-bottom: 30px; }
            .footer { margin-top: 30px; color: #666; font-size: 12px; }
          </style>
        </head>
        <body>
          <h1>Guardian Verification System Report</h1>
          <p>Generated: ${reportData.generatedAt}</p>
          
          <div class="section">
            <h2>Students Summary</h2>
            <p>Total Students: ${students.length}</p>
            <table>
              <tr>
                <th>Barcode</th>
                <th>Name</th>
                <th>DOB</th>
                <th>Guardian</th>
              </tr>
              ${students.map(s => `
                <tr>
                  <td>${s.barcode}</td>
                  <td>${s.firstName} ${s.lastName}</td>
                  <td>${s.dateOfBirth}</td>
                  <td>${s.guardianFirstName} ${s.guardianLastName}</td>
                </tr>
              `).join('')}
            </table>
          </div>

          <div class="section">
            <h2>Guardians Summary</h2>
            <p>Total Guardians: ${guardians.length}</p>
            <table>
              <tr>
                <th>Barcode</th>
                <th>Name</th>
                <th>Contact</th>
                <th>Relationship</th>
              </tr>
              ${guardians.map(g => `
                <tr>
                  <td>${g.barcode}</td>
                  <td>${g.firstName} ${g.lastName}</td>
                  <td>${g.contactNumber}</td>
                  <td>${g.relationship}</td>
                </tr>
              `).join('')}
            </table>
          </div>

          <div class="footer">
            <p>This report was generated by Guardian Verification System</p>
          </div>
        </body>
      </html>
    `;

    const printWindow = window.open('', '', 'width=1000,height=600');
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <h1>Admin Dashboard</h1>
        <p>Guardian Verification System Management</p>
      </div>

      {error && <div className="alert alert-danger">{error}</div>}

      <div className="dashboard-stats">
        <div className="stat-card">
          <div className="stat-icon">👥</div>
          <div className="stat-content">
            <div className="stat-label">Total Students</div>
            <div className="stat-value">{students.length}</div>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon">🛡️</div>
          <div className="stat-content">
            <div className="stat-label">Total Guardians</div>
            <div className="stat-value">{guardians.length}</div>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon">✓</div>
          <div className="stat-content">
            <div className="stat-label">Verify Success Rate</div>
            <div className="stat-value">
              {logs.length > 0 
                ? Math.round((logs.filter(l => l.verificationStatus === 'SUCCESS').length / logs.length) * 100)
                : 0}%
            </div>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon">📋</div>
          <div className="stat-content">
            <div className="stat-label">Total Verifications</div>
            <div className="stat-value">{logs.length}</div>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon">✅</div>
          <div className="stat-content">
            <div className="stat-label">Successful Verifications</div>
            <div className="stat-value">{logs.filter(l => l.verificationStatus === 'SUCCESS').length}</div>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon">❌</div>
          <div className="stat-content">
            <div className="stat-label">Failed Verifications</div>
            <div className="stat-value">{logs.filter(l => l.verificationStatus === 'FAILED').length}</div>
          </div>
        </div>
      </div>

      {loading ? (
        <div className="loading">Loading data...</div>
      ) : (
        <>
          <div className="dashboard-grid">
            {/* Students Table */}
            <div className="table-section">
              <div className="section-header">
                <h2>Recent Students</h2>
                <span className="badge">{students.length}</span>
              </div>
              {students.length > 0 ? (
                <div className="table-wrapper">
                  <table>
                    <thead>
                      <tr>
                        <th>Barcode</th>
                        <th>Name</th>
                        <th>Date of Birth</th>
                        <th>Guardian</th>
                        <th>Registration Date</th>
                      </tr>
                    </thead>
                    <tbody>
                      {students.slice(0, 10).map((student, index) => (
                        <tr key={index}>
                          <td>
                            <code>{student.barcode}</code>
                          </td>
                          <td>{student.firstName} {student.lastName}</td>
                          <td>{new Date(student.dateOfBirth).toLocaleDateString()}</td>
                          <td>{student.guardianFirstName} {student.guardianLastName}</td>
                          <td>{new Date(student.registrationDate).toLocaleDateString()}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <p className="empty-state">No students registered yet</p>
              )}
            </div>

            {/* Guardians Table */}
            <div className="table-section">
              <div className="section-header">
                <h2>Recent Guardians</h2>
                <span className="badge">{guardians.length}</span>
              </div>
              {guardians.length > 0 ? (
                <div className="table-wrapper">
                  <table>
                    <thead>
                      <tr>
                        <th>Barcode</th>
                        <th>Name</th>
                        <th>Contact</th>
                        <th>Relationship</th>
                        <th>Registration Date</th>
                      </tr>
                    </thead>
                    <tbody>
                      {guardians.slice(0, 10).map((guardian, index) => (
                        <tr key={index}>
                          <td>
                            <code>{guardian.barcode}</code>
                          </td>
                          <td>{guardian.firstName} {guardian.lastName}</td>
                          <td>{guardian.contactNumber}</td>
                          <td>{guardian.relationship}</td>
                          <td>{new Date(guardian.registrationDate).toLocaleDateString()}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <p className="empty-state">No guardians registered yet</p>
              )}
            </div>
          </div>

          <div className="action-section">
            <button className="btn btn-primary btn-large" onClick={handlePrintReport}>
              🖨️ Print Report
            </button>
            <button className="btn btn-secondary btn-large" onClick={loadData}>
              ↻ Refresh Data
            </button>
          </div>
        </>
      )}
    </div>
  );
}

export default AdminDashboard;
