import React, { useState, useEffect } from 'react';
import './VerificationLogs.css';

function VerificationLogs() {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [filter, setFilter] = useState('all');

  useEffect(() => {
    loadLogs();
  }, []);

  const loadLogs = async () => {
    setLoading(true);
    setError('');
    try {
      const result = await window.electron.getVerificationLogs();
      if (result.success) {
        setLogs(result.data || []);
      } else {
        setError(result.error || 'Failed to load logs');
      }
    } catch (err) {
      setError('Error loading logs: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const filteredLogs = logs.filter((log) => {
    if (filter === 'success') return log.verificationStatus === 'SUCCESS';
    if (filter === 'failed') return log.verificationStatus === 'FAILED';
    return true;
  });

  const successCount = logs.filter((l) => l.verificationStatus === 'SUCCESS').length;
  const failedCount = logs.filter((l) => l.verificationStatus === 'FAILED').length;
  const successRate = logs.length > 0 ? Math.round((successCount / logs.length) * 100) : 0;

  const handlePrintLogs = () => {
    const content = `
      <html>
        <head>
          <title>Verification Logs Report</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { color: #667eea; }
            table { border-collapse: collapse; width: 100%; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
            th { background: #667eea; color: white; }
            .success { background: #d4edda; }
            .failed { background: #f8d7da; }
            .stats { margin: 20px 0; }
            .footer { margin-top: 30px; color: #666; font-size: 12px; }
          </style>
        </head>
        <body>
          <h1>Verification Logs Report</h1>
          <p>Generated: ${new Date().toLocaleString()}</p>
          
          <div class="stats">
            <h3>Summary</h3>
            <p>Total Verifications: ${logs.length}</p>
            <p>Successful: ${successCount}</p>
            <p>Failed: ${failedCount}</p>
            <p>Success Rate: ${successRate}%</p>
          </div>

          <table>
            <tr>
              <th>Date/Time</th>
              <th>Student</th>
              <th>Guardian</th>
              <th>Status</th>
            </tr>
            ${filteredLogs.map((log) => `
              <tr class="${log.verificationStatus.toLowerCase()}">
                <td>${new Date(log.verificationTime).toLocaleString()}</td>
                <td>${log.studentFirstName} ${log.studentLastName}</td>
                <td>${log.guardianFirstName} ${log.guardianLastName}</td>
                <td>${log.verificationStatus}</td>
              </tr>
            `).join('')}
          </table>

          <div class="footer">
            <p>This report was generated by Guardian Verification System</p>
          </div>
        </body>
      </html>
    `;

    const printWindow = window.open('', '', 'width=1000,height=600');
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="logs-container">
      <div className="logs-header">
        <h1>Verification Logs</h1>
        <p>Track all guardian verification attempts</p>
      </div>

      {error && <div className="alert alert-danger">{error}</div>}

      {loading ? (
        <div className="loading">Loading logs...</div>
      ) : (
        <>
          <div className="logs-section">
            <div className="logs-header-row">
              <h2>Verification Records</h2>
              <div className="filters">
                <button
                  className={`filter-btn ${filter === 'all' ? 'active' : ''}`}
                  onClick={() => setFilter('all')}
                >
                  All ({logs.length})
                </button>
                <button
                  className={`filter-btn ${filter === 'success' ? 'active' : ''}`}
                  onClick={() => setFilter('success')}
                >
                  Success ({successCount})
                </button>
                <button
                  className={`filter-btn ${filter === 'failed' ? 'active' : ''}`}
                  onClick={() => setFilter('failed')}
                >
                  Failed ({failedCount})
                </button>
              </div>
            </div>

            {filteredLogs.length > 0 ? (
              <div className="table-wrapper">
                <table>
                  <thead>
                    <tr>
                      <th>Date & Time</th>
                      <th>Student</th>
                      <th>Guardian</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredLogs.map((log, index) => (
                      <tr key={index} className={`status-${log.verificationStatus.toLowerCase()}`}>
                        <td>{new Date(log.verificationTime).toLocaleString()}</td>
                        <td>
                          <div className="name">
                            {log.studentFirstName} {log.studentLastName}
                          </div>
                          <small>{log.studentBarcode}</small>
                        </td>
                        <td>
                          <div className="name">
                            {log.guardianFirstName} {log.guardianLastName}
                          </div>
                          <small>{log.guardianBarcode}</small>
                        </td>
                        <td>
                          <span className={`status-badge ${log.verificationStatus.toLowerCase()}`}>
                            {log.verificationStatus}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <p className="empty-state">No verification logs found</p>
            )}
          </div>

          <div className="logs-actions">
            <button className="btn btn-primary" onClick={loadLogs}>
              ↻ Refresh Logs
            </button>
            <button className="btn btn-secondary" onClick={handlePrintLogs} disabled={logs.length === 0}>
              🖨️ Print Report
            </button>
          </div>
        </>
      )}
    </div>
  );
}

export default VerificationLogs;
